### ISSUE TITLE
Outdated runtime

### ISSUE THREAD

**Issue by RayJW** [flathub/com.github.dail8859.NotepadNext#25] opened 2024-05-07 19:28 UTC
```
Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   com.github.dail8859.NotepadNext
```

While I am aware, that NotepadNext currently isn't build with the newest QT, I'm not aware if that affects building with a newer runtime.

**Comment by zocker-160** [comment] 2024-05-07 22:07
Duplicate of https://github.com/dail8859/NotepadNext/issues/550.
Moving away from 6.5 is currently blocked, see: https://github.com/flathub/com.github.dail8859.NotepadNext/pull/24#issuecomment-2085061158

Qt 6.6 is available in flathub-beta if you want it regardless.

**Closed as not planned by zocker-160** 2024-05-07 22:07 UTC

**Comment by Justinzobel** [comment] 2024-11-02 05:40
The application runs on the same platform it uses to build. So if it uses the 6.5 SDK to build, it will run on Platform 6.5. 

Please consider updating the runtime you are currently using as it is EOL (End Of Life) meaning there will be no further updates of any kind, including security.

**Comment by zocker-160** [comment] 2024-11-02 11:33
As stated above, updating the runtime is blocked due to regressions in functionality.

If it wasn't for this annoying warning, nobody would care.

**Comment by Justinzobel** [comment] 2024-11-03 01:30
I care not because of the warning, but because I want all apps to move to supported runtimes. I don't even use this app. I'm just part of the KDE team that creates/manages the runtimes. I also want Flatpak/Flathub to succeed, so making sure uses the latest possible runtime to avoid these warnings helps improve adoption.

**Comment by dail8859** [comment] 2024-11-03 02:32
Since there are currently blockers for Qt 6.5+ as stated above, what are you suggesting then? Remove the app?

**Comment by Justinzobel** [comment] 2024-11-03 02:38
No of course not, if it's pending upstream work then there's nothing to do yet other than work with upstream to get it tested and implemented as soon as possible.
